"""Generate the mechanical rename inventory from canonical pyproject metadata."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = "docs/rename-inventory.md"


def inventory(root):
    metadata = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    command, entrypoint = next(iter(metadata["scripts"].items()))
    package = entrypoint.split(".")[0]
    tokens = [
        metadata["name"],
        metadata["name"].replace("-", "_"),
        command,
        package,
        metadata["urls"]["Repository"],
    ]
    pattern = re.compile(
        "|".join(re.escape(t) for t in sorted(set(tokens), key=len, reverse=True)), re.I
    )
    names = subprocess.check_output(["git", "ls-files", "-z"], cwd=root).decode().split("\0")
    rows = []
    for name in sorted(filter(None, names)):
        if name in (DESTINATION, "docs/rename-consumer-inventory.md"):
            continue
        path = root / name
        if not path.is_file():
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        matches = [str(i) for i, text in enumerate(lines, 1) if pattern.search(text)]
        if matches or pattern.search(name):
            rows.append(f"| `{name}` | {', '.join(matches) or 'path only'} |")
    return "\n".join(rows)


def render():
    return (
        """# Rename inventory (provisional identity)

Generated by `python tools/rename_inventory.py`; do not hand-edit the tables.
`pyproject.toml` is the canonical distribution/CLI/import/repository identity:
`project.name`, `project.scripts` key, its entrypoint module root, and
`project.urls.Repository`. Release versions and immutable artifact identities are
pinned separately in `docs/release-pins.json`. No final name is selected here.

POK-645 procedure after Sahel's decision:

1. Change those canonical metadata fields together; move the import directory and
   update imports, module strings, entrypoints, package-data and tooling paths.
2. Replace identity literals at the lines below (case-insensitive matching also
   finds environment prefixes, Windows commands, service/keyring names and branding).
   Decide explicit compatibility aliases and state/keyring migration before changing
   persisted identities; never silently abandon existing installations or credentials.
3. Replace live repository, badge, workflow and installation URLs only after the
   corresponding repositories/assets exist. Keep historical provenance/attribution,
   release pins, snapshots and rollback inputs immutable and label them as historical.
4. Regenerate contract exports, scaffold golden hashes, installed-resource/API
   snapshots, consumer constraints and release filenames using their owning tools/tests.
   Do not blind-replace hashes, attestations or old-version compatibility fixtures.
5. Inventory the scripts consumer with `--consumer PATH` and update its verified
   constraints/bootstrap/docs only after the renamed release is verified. Rehearse
   the old-to-new upgrade and rollback; rerun all three-OS certification jobs.
6. Regenerate this inventory and review every remaining old-name hit. Configure
   publishing only under POK-645's separate owner-approved launch gate.

Every row identifies an exact tracked file and matching content lines; matching
path names are included even without content matches. Binary assets are excluded
(the repository currently has no identity-bearing binary logos). Both generated inventory documents
are excluded to avoid self-reference. Line numbers are revision-specific.

| Framework file | Matching lines |
| --- | --- |
"""
        + inventory(ROOT)
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--consumer", type=Path)
    args = parser.parse_args()
    if args.consumer:
        commit = (
            subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=args.consumer)
            .decode()
            .strip()
        )
        print(
            "# Consumer rename inventory\n\n"
            f"Original scripts consumer at `{commit}`. Generated with "
            "`python tools/rename_inventory.py --consumer PATH`. Apply the mechanisms in "
            "[the framework inventory](rename-inventory.md); immutable historical evidence "
            "and release hashes must not be blindly replaced.\n\n"
            "| Consumer file | Matching lines |\n| --- | --- |\n" + inventory(args.consumer)
        )
        return
    destination = ROOT / DESTINATION
    content = render()
    if args.check:
        assert destination.read_text(encoding="utf-8") == content, "regenerate rename inventory"
    else:
        destination.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
